CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SENSOR=y  

# Always assert, defensive programming
CONFIG_ASSERT=y
CONFIG_ASSERT_VERBOSE=n

# Logging and shell configuration
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_SHELL=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# zbus configuration
CONFIG_ZBUS=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_CHANNELS_SYS_INIT_PRIORITY=1

# Display and user interaction configuration
CONFIG_DISPLAY=y
CONFIG_INPUT=y

# LVGL configuration
CONFIG_LVGL=y
CONFIG_LV_USE_OBJ_ID=y
CONFIG_LV_USE_OBJ_NAME=y
CONFIG_LV_USE_OBJ_ID_BUILTIN=y
CONFIG_LV_USE_OBSERVER=y
CONFIG_LV_Z_SHELL=y
CONFIG_LV_Z_MEM_POOL_SIZE=81920

# Tell LVGL to use a monochrome style for GUI
CONFIG_LV_USE_THEME_MONO=y

# LVGL Fonts
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_FONT_MONTSERRAT_24=y
