CONFIG_EMUL=y
CONFIG_GPIO_EMUL=y
CONFIG_I2C_EMUL=y

#CONFIG_SDL_DISPLAY_ZOOM_PCT=200

# For simulating a monochrome display
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_SDL_DISPLAY_DEFAULT_PIXEL_FORMAT_MONO10=y

# Set the main logging level to print everything except debug
CONFIG_LOG_DEFAULT_LEVEL=3
# Set the local logging configuration to print everything
CONFIG_TAT_APPLICATIONS_LOG_LEVEL_DBG=y
CONFIG_TAT_MANAGERS_LOG_LEVEL_DBG=y
CONFIG_TAT_SENSORS_LOG_LEVEL_DBG=y
CONFIG_TAT_UI_LOG_LEVEL_DBG=y

# For LVGL debugging
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_ERROR=y
#CONFIG_INPUT_EVENT_DUMP=y

# For simulating a color display
#CONFIG_LV_COLOR_DEPTH_32=y